### ISSUE TITLE
State of this repo? 

### ISSUE THREAD

**Issue by epinault** [allegro/ecto-cursor-based-stream#11]
@jtomaszewski are you still maintaining it? I opened a PR a while back and still not merge. Do you need help maintaining it? We use it in our company and we would be ok to help provide resources if you give us Maintainer access

**Comment by jtomaszewski** [comment]
I've left Allegro and I don't work with Elixir currently, so I might not be the best person for it. But the team is still there and using this library.

@alukasz do you know if somebody can answer this? And merge https://github.com/allegro/ecto-cursor-based-stream/pull/9 which looks good IMHO.

**Comment by alukasz** [comment]
Hi, I got access to this repo for Elixir team at Allegro, I'll merge that PR. @epinault we will maintain this repo, if you need anything feel free to open PR.
