### ISSUE TITLE
Examples link broken on HexDocs

### ISSUE THREAD

**Issue by Stratus3D** [allegro/ecto-cursor-based-stream#8]
![Screenshot 2023-03-15 at 20-15-16 EctoCursorBasedStream — ecto_cursor_based_stream v1 0 1](https://user-images.githubusercontent.com/1520926/225476342-f0123851-1bd9-4ca7-bbf4-c29565359067.png)

The "Examples" link on the readme works, but the one in the HexDocs does not.

**Comment by jtomaszewski** [comment]
Thanks, fixed in v1.0.2 .
